//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundaAppTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FundaAppTests.ResourceTestData", typeof(ResourceTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Raymond&quot;:0,&quot;EmailNotConfirmed&quot;:false,&quot;ValidationFailed&quot;:false,&quot;ValidationReport&quot;:null,&quot;Website&quot;:0,&quot;Metadata&quot;:{&quot;ObjectType&quot;:&quot;Koopwoningen&quot;,&quot;Omschrijving&quot;:&quot;Koopwoningen &gt; Amsterdam | Tuin&quot;,&quot;Titel&quot;:&quot;Huizen te koop in Amsterdam&quot;},&quot;Objects&quot;:[{&quot;AangebodenSindsTekst&quot;:&quot;Vandaag&quot;,&quot;AanmeldDatum&quot;:&quot;\/Date(1262300400000+0100)\/&quot;,&quot;AantalBeschikbaar&quot;:null,&quot;AantalKamers&quot;:5,&quot;AantalKavels&quot;:null,&quot;Aanvaarding&quot;:&quot;InOverleg&quot;,&quot;Adres&quot;:&quot;Vegastraat 219&quot;,&quot;Afstand&quot;:0,&quot;BronCode&quot;:&quot;NVM&quot;,&quot;ChildrenObjects&quot;:[],&quot;DatumAanvaarding&quot;:null,&quot;Datum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonResponseNoPagingClass {
            get {
                return ResourceManager.GetString("JsonResponseNoPagingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Raymond&quot;:0,&quot;EmailNotConfirmed&quot;:false,&quot;ValidationFailed&quot;:false,&quot;ValidationReport&quot;:null,&quot;Website&quot;:0,&quot;Metadata&quot;:{&quot;ObjectType&quot;:&quot;Koopwoningen&quot;,&quot;Omschrijving&quot;:&quot;Koopwoningen &gt; Amsterdam | Tuin&quot;,&quot;Titel&quot;:&quot;Huizen te koop in Amsterdam&quot;},&quot;Objects&quot;:[{&quot;AangebodenSindsTekst&quot;:&quot;Vandaag&quot;,&quot;AanmeldDatum&quot;:&quot;\/Date(1262300400000+0100)\/&quot;,&quot;AantalBeschikbaar&quot;:null,&quot;AantalKamers&quot;:5,&quot;AantalKavels&quot;:null,&quot;Aanvaarding&quot;:&quot;InOverleg&quot;,&quot;Adres&quot;:&quot;Vegastraat 219&quot;,&quot;Afstand&quot;:0,&quot;BronCode&quot;:&quot;NVM&quot;,&quot;ChildrenObjects&quot;:[],&quot;DatumAanvaarding&quot;:null,&quot;Datum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonResponseOK {
            get {
                return ResourceManager.GetString("JsonResponseOK", resourceCulture);
            }
        }
    }
}
